kind: PersistentVolumeClaim
apiVersion: v1
metadate:
  labels:
    app: uptime-kuma
  name: uptime-kuma-pvc
  namespace: uptime-kuma
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
